// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: wingsv/proto/wingsv.proto

package wingsvproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigType int32

const (
	ConfigType_CONFIG_TYPE_UNSPECIFIED ConfigType = 0
	ConfigType_CONFIG_TYPE_VK          ConfigType = 1
	ConfigType_CONFIG_TYPE_XRAY        ConfigType = 2
	ConfigType_CONFIG_TYPE_AMNEZIAWG   ConfigType = 3
)

// Enum value maps for ConfigType.
var (
	ConfigType_name = map[int32]string{
		0: "CONFIG_TYPE_UNSPECIFIED",
		1: "CONFIG_TYPE_VK",
		2: "CONFIG_TYPE_XRAY",
		3: "CONFIG_TYPE_AMNEZIAWG",
	}
	ConfigType_value = map[string]int32{
		"CONFIG_TYPE_UNSPECIFIED": 0,
		"CONFIG_TYPE_VK":          1,
		"CONFIG_TYPE_XRAY":        2,
		"CONFIG_TYPE_AMNEZIAWG":   3,
	}
)

func (x ConfigType) Enum() *ConfigType {
	p := new(ConfigType)
	*p = x
	return p
}

func (x ConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_wingsv_proto_wingsv_proto_enumTypes[0].Descriptor()
}

func (ConfigType) Type() protoreflect.EnumType {
	return &file_wingsv_proto_wingsv_proto_enumTypes[0]
}

func (x ConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigType.Descriptor instead.
func (ConfigType) EnumDescriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{0}
}

type BackendType int32

const (
	BackendType_BACKEND_TYPE_UNSPECIFIED       BackendType = 0
	BackendType_BACKEND_TYPE_VK_TURN_WIREGUARD BackendType = 1
	BackendType_BACKEND_TYPE_XRAY              BackendType = 2
	BackendType_BACKEND_TYPE_AMNEZIAWG         BackendType = 3
)

// Enum value maps for BackendType.
var (
	BackendType_name = map[int32]string{
		0: "BACKEND_TYPE_UNSPECIFIED",
		1: "BACKEND_TYPE_VK_TURN_WIREGUARD",
		2: "BACKEND_TYPE_XRAY",
		3: "BACKEND_TYPE_AMNEZIAWG",
	}
	BackendType_value = map[string]int32{
		"BACKEND_TYPE_UNSPECIFIED":       0,
		"BACKEND_TYPE_VK_TURN_WIREGUARD": 1,
		"BACKEND_TYPE_XRAY":              2,
		"BACKEND_TYPE_AMNEZIAWG":         3,
	}
)

func (x BackendType) Enum() *BackendType {
	p := new(BackendType)
	*p = x
	return p
}

func (x BackendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackendType) Descriptor() protoreflect.EnumDescriptor {
	return file_wingsv_proto_wingsv_proto_enumTypes[1].Descriptor()
}

func (BackendType) Type() protoreflect.EnumType {
	return &file_wingsv_proto_wingsv_proto_enumTypes[1]
}

func (x BackendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackendType.Descriptor instead.
func (BackendType) EnumDescriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{1}
}

type TurnSessionMode int32

const (
	TurnSessionMode_TURN_SESSION_MODE_UNSPECIFIED TurnSessionMode = 0
	TurnSessionMode_TURN_SESSION_MODE_AUTO        TurnSessionMode = 1
	TurnSessionMode_TURN_SESSION_MODE_MAINLINE    TurnSessionMode = 2
	TurnSessionMode_TURN_SESSION_MODE_MUX         TurnSessionMode = 3
)

// Enum value maps for TurnSessionMode.
var (
	TurnSessionMode_name = map[int32]string{
		0: "TURN_SESSION_MODE_UNSPECIFIED",
		1: "TURN_SESSION_MODE_AUTO",
		2: "TURN_SESSION_MODE_MAINLINE",
		3: "TURN_SESSION_MODE_MUX",
	}
	TurnSessionMode_value = map[string]int32{
		"TURN_SESSION_MODE_UNSPECIFIED": 0,
		"TURN_SESSION_MODE_AUTO":        1,
		"TURN_SESSION_MODE_MAINLINE":    2,
		"TURN_SESSION_MODE_MUX":         3,
	}
)

func (x TurnSessionMode) Enum() *TurnSessionMode {
	p := new(TurnSessionMode)
	*p = x
	return p
}

func (x TurnSessionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TurnSessionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_wingsv_proto_wingsv_proto_enumTypes[2].Descriptor()
}

func (TurnSessionMode) Type() protoreflect.EnumType {
	return &file_wingsv_proto_wingsv_proto_enumTypes[2]
}

func (x TurnSessionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TurnSessionMode.Descriptor instead.
func (TurnSessionMode) EnumDescriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{2}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ver           uint32                 `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Type          ConfigType             `protobuf:"varint,2,opt,name=type,proto3,enum=wingsv.ConfigType" json:"type,omitempty"`
	Turn          *Turn                  `protobuf:"bytes,3,opt,name=turn,proto3" json:"turn,omitempty"`
	Wg            *WireGuard             `protobuf:"bytes,4,opt,name=wg,proto3" json:"wg,omitempty"`
	Backend       BackendType            `protobuf:"varint,5,opt,name=backend,proto3,enum=wingsv.BackendType" json:"backend,omitempty"`
	Xray          *Xray                  `protobuf:"bytes,6,opt,name=xray,proto3" json:"xray,omitempty"`
	Awg           *AmneziaWG             `protobuf:"bytes,7,opt,name=awg,proto3" json:"awg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *Config) GetType() ConfigType {
	if x != nil {
		return x.Type
	}
	return ConfigType_CONFIG_TYPE_UNSPECIFIED
}

func (x *Config) GetTurn() *Turn {
	if x != nil {
		return x.Turn
	}
	return nil
}

func (x *Config) GetWg() *WireGuard {
	if x != nil {
		return x.Wg
	}
	return nil
}

func (x *Config) GetBackend() BackendType {
	if x != nil {
		return x.Backend
	}
	return BackendType_BACKEND_TYPE_UNSPECIFIED
}

func (x *Config) GetXray() *Xray {
	if x != nil {
		return x.Xray
	}
	return nil
}

func (x *Config) GetAwg() *AmneziaWG {
	if x != nil {
		return x.Awg
	}
	return nil
}

type AmneziaWG struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AwgQuickConfig string                 `protobuf:"bytes,1,opt,name=awg_quick_config,json=awgQuickConfig,proto3" json:"awg_quick_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AmneziaWG) Reset() {
	*x = AmneziaWG{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmneziaWG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmneziaWG) ProtoMessage() {}

func (x *AmneziaWG) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmneziaWG.ProtoReflect.Descriptor instead.
func (*AmneziaWG) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{1}
}

func (x *AmneziaWG) GetAwgQuickConfig() string {
	if x != nil {
		return x.AwgQuickConfig
	}
	return ""
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{2}
}

func (x *Endpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Cidr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          []byte                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Prefix        uint32                 `protobuf:"varint,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cidr) Reset() {
	*x = Cidr{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cidr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cidr) ProtoMessage() {}

func (x *Cidr) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cidr.ProtoReflect.Descriptor instead.
func (*Cidr) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{3}
}

func (x *Cidr) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *Cidr) GetPrefix() uint32 {
	if x != nil {
		return x.Prefix
	}
	return 0
}

type Turn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *Endpoint              `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Threads       *uint32                `protobuf:"varint,3,opt,name=threads,proto3,oneof" json:"threads,omitempty"`
	UseUdp        *bool                  `protobuf:"varint,4,opt,name=use_udp,json=useUdp,proto3,oneof" json:"use_udp,omitempty"`
	NoObfuscation *bool                  `protobuf:"varint,5,opt,name=no_obfuscation,json=noObfuscation,proto3,oneof" json:"no_obfuscation,omitempty"`
	LocalEndpoint *Endpoint              `protobuf:"bytes,6,opt,name=local_endpoint,json=localEndpoint,proto3" json:"local_endpoint,omitempty"`
	Host          string                 `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
	Port          *uint32                `protobuf:"varint,8,opt,name=port,proto3,oneof" json:"port,omitempty"`
	SessionMode   TurnSessionMode        `protobuf:"varint,9,opt,name=session_mode,json=sessionMode,proto3,enum=wingsv.TurnSessionMode" json:"session_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{4}
}

func (x *Turn) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *Turn) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Turn) GetThreads() uint32 {
	if x != nil && x.Threads != nil {
		return *x.Threads
	}
	return 0
}

func (x *Turn) GetUseUdp() bool {
	if x != nil && x.UseUdp != nil {
		return *x.UseUdp
	}
	return false
}

func (x *Turn) GetNoObfuscation() bool {
	if x != nil && x.NoObfuscation != nil {
		return *x.NoObfuscation
	}
	return false
}

func (x *Turn) GetLocalEndpoint() *Endpoint {
	if x != nil {
		return x.LocalEndpoint
	}
	return nil
}

func (x *Turn) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Turn) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *Turn) GetSessionMode() TurnSessionMode {
	if x != nil {
		return x.SessionMode
	}
	return TurnSessionMode_TURN_SESSION_MODE_UNSPECIFIED
}

type WireGuard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iface         *Interface             `protobuf:"bytes,1,opt,name=iface,proto3" json:"iface,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireGuard) Reset() {
	*x = WireGuard{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuard) ProtoMessage() {}

func (x *WireGuard) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuard.ProtoReflect.Descriptor instead.
func (*WireGuard) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{5}
}

func (x *WireGuard) GetIface() *Interface {
	if x != nil {
		return x.Iface
	}
	return nil
}

func (x *WireGuard) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type Interface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    []byte                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Dns           []string               `protobuf:"bytes,3,rep,name=dns,proto3" json:"dns,omitempty"`
	Mtu           *uint32                `protobuf:"varint,4,opt,name=mtu,proto3,oneof" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{6}
}

func (x *Interface) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *Interface) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Interface) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *Interface) GetMtu() uint32 {
	if x != nil && x.Mtu != nil {
		return *x.Mtu
	}
	return 0
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PresharedKey  []byte                 `protobuf:"bytes,2,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	AllowedIps    []*Cidr                `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{7}
}

func (x *Peer) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Peer) GetPresharedKey() []byte {
	if x != nil {
		return x.PresharedKey
	}
	return nil
}

func (x *Peer) GetAllowedIps() []*Cidr {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

type Xray struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActiveProfileId  string                 `protobuf:"bytes,1,opt,name=active_profile_id,json=activeProfileId,proto3" json:"active_profile_id,omitempty"`
	Profiles         []*VlessProfile        `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Subscriptions    []*Subscription        `protobuf:"bytes,3,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Settings         *XraySettings          `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
	SubscriptionJson string                 `protobuf:"bytes,5,opt,name=subscription_json,json=subscriptionJson,proto3" json:"subscription_json,omitempty"`
	MergeOnly        *bool                  `protobuf:"varint,6,opt,name=merge_only,json=mergeOnly,proto3,oneof" json:"merge_only,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Xray) Reset() {
	*x = Xray{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Xray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Xray) ProtoMessage() {}

func (x *Xray) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Xray.ProtoReflect.Descriptor instead.
func (*Xray) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{8}
}

func (x *Xray) GetActiveProfileId() string {
	if x != nil {
		return x.ActiveProfileId
	}
	return ""
}

func (x *Xray) GetProfiles() []*VlessProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *Xray) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *Xray) GetSettings() *XraySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Xray) GetSubscriptionJson() string {
	if x != nil {
		return x.SubscriptionJson
	}
	return ""
}

func (x *Xray) GetMergeOnly() bool {
	if x != nil && x.MergeOnly != nil {
		return *x.MergeOnly
	}
	return false
}

type Subscription struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	FormatHint           string                 `protobuf:"bytes,4,opt,name=format_hint,json=formatHint,proto3" json:"format_hint,omitempty"`
	RefreshIntervalHours *uint32                `protobuf:"varint,5,opt,name=refresh_interval_hours,json=refreshIntervalHours,proto3,oneof" json:"refresh_interval_hours,omitempty"`
	AutoUpdate           *bool                  `protobuf:"varint,6,opt,name=auto_update,json=autoUpdate,proto3,oneof" json:"auto_update,omitempty"`
	LastUpdatedAt        *int64                 `protobuf:"varint,7,opt,name=last_updated_at,json=lastUpdatedAt,proto3,oneof" json:"last_updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{9}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Subscription) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Subscription) GetFormatHint() string {
	if x != nil {
		return x.FormatHint
	}
	return ""
}

func (x *Subscription) GetRefreshIntervalHours() uint32 {
	if x != nil && x.RefreshIntervalHours != nil {
		return *x.RefreshIntervalHours
	}
	return 0
}

func (x *Subscription) GetAutoUpdate() bool {
	if x != nil && x.AutoUpdate != nil {
		return *x.AutoUpdate
	}
	return false
}

func (x *Subscription) GetLastUpdatedAt() int64 {
	if x != nil && x.LastUpdatedAt != nil {
		return *x.LastUpdatedAt
	}
	return 0
}

type VlessProfile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	RawLink           string                 `protobuf:"bytes,3,opt,name=raw_link,json=rawLink,proto3" json:"raw_link,omitempty"`
	SubscriptionId    string                 `protobuf:"bytes,4,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	SubscriptionTitle string                 `protobuf:"bytes,5,opt,name=subscription_title,json=subscriptionTitle,proto3" json:"subscription_title,omitempty"`
	Address           string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Port              *uint32                `protobuf:"varint,7,opt,name=port,proto3,oneof" json:"port,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VlessProfile) Reset() {
	*x = VlessProfile{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlessProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlessProfile) ProtoMessage() {}

func (x *VlessProfile) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlessProfile.ProtoReflect.Descriptor instead.
func (*VlessProfile) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{10}
}

func (x *VlessProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VlessProfile) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VlessProfile) GetRawLink() string {
	if x != nil {
		return x.RawLink
	}
	return ""
}

func (x *VlessProfile) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *VlessProfile) GetSubscriptionTitle() string {
	if x != nil {
		return x.SubscriptionTitle
	}
	return ""
}

func (x *VlessProfile) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VlessProfile) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

type XraySettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AllowLan        *bool                  `protobuf:"varint,1,opt,name=allow_lan,json=allowLan,proto3,oneof" json:"allow_lan,omitempty"`
	AllowInsecure   *bool                  `protobuf:"varint,2,opt,name=allow_insecure,json=allowInsecure,proto3,oneof" json:"allow_insecure,omitempty"`
	LocalProxyPort  *uint32                `protobuf:"varint,3,opt,name=local_proxy_port,json=localProxyPort,proto3,oneof" json:"local_proxy_port,omitempty"`
	RemoteDns       string                 `protobuf:"bytes,4,opt,name=remote_dns,json=remoteDns,proto3" json:"remote_dns,omitempty"`
	DirectDns       string                 `protobuf:"bytes,5,opt,name=direct_dns,json=directDns,proto3" json:"direct_dns,omitempty"`
	Ipv6            *bool                  `protobuf:"varint,6,opt,name=ipv6,proto3,oneof" json:"ipv6,omitempty"`
	SniffingEnabled *bool                  `protobuf:"varint,7,opt,name=sniffing_enabled,json=sniffingEnabled,proto3,oneof" json:"sniffing_enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *XraySettings) Reset() {
	*x = XraySettings{}
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XraySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XraySettings) ProtoMessage() {}

func (x *XraySettings) ProtoReflect() protoreflect.Message {
	mi := &file_wingsv_proto_wingsv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XraySettings.ProtoReflect.Descriptor instead.
func (*XraySettings) Descriptor() ([]byte, []int) {
	return file_wingsv_proto_wingsv_proto_rawDescGZIP(), []int{11}
}

func (x *XraySettings) GetAllowLan() bool {
	if x != nil && x.AllowLan != nil {
		return *x.AllowLan
	}
	return false
}

func (x *XraySettings) GetAllowInsecure() bool {
	if x != nil && x.AllowInsecure != nil {
		return *x.AllowInsecure
	}
	return false
}

func (x *XraySettings) GetLocalProxyPort() uint32 {
	if x != nil && x.LocalProxyPort != nil {
		return *x.LocalProxyPort
	}
	return 0
}

func (x *XraySettings) GetRemoteDns() string {
	if x != nil {
		return x.RemoteDns
	}
	return ""
}

func (x *XraySettings) GetDirectDns() string {
	if x != nil {
		return x.DirectDns
	}
	return ""
}

func (x *XraySettings) GetIpv6() bool {
	if x != nil && x.Ipv6 != nil {
		return *x.Ipv6
	}
	return false
}

func (x *XraySettings) GetSniffingEnabled() bool {
	if x != nil && x.SniffingEnabled != nil {
		return *x.SniffingEnabled
	}
	return false
}

var File_wingsv_proto_wingsv_proto protoreflect.FileDescriptor

const file_wingsv_proto_wingsv_proto_rawDesc = "" +
	"\n" +
	"\x19wingsv/proto/wingsv.proto\x12\x06wingsv\"\xfd\x01\n" +
	"\x06Config\x12\x10\n" +
	"\x03ver\x18\x01 \x01(\rR\x03ver\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.wingsv.ConfigTypeR\x04type\x12 \n" +
	"\x04turn\x18\x03 \x01(\v2\f.wingsv.TurnR\x04turn\x12!\n" +
	"\x02wg\x18\x04 \x01(\v2\x11.wingsv.WireGuardR\x02wg\x12-\n" +
	"\abackend\x18\x05 \x01(\x0e2\x13.wingsv.BackendTypeR\abackend\x12 \n" +
	"\x04xray\x18\x06 \x01(\v2\f.wingsv.XrayR\x04xray\x12#\n" +
	"\x03awg\x18\a \x01(\v2\x11.wingsv.AmneziaWGR\x03awg\"5\n" +
	"\tAmneziaWG\x12(\n" +
	"\x10awg_quick_config\x18\x01 \x01(\tR\x0eawgQuickConfig\"2\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"2\n" +
	"\x04Cidr\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\fR\x04addr\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\rR\x06prefix\"\x87\x03\n" +
	"\x04Turn\x12,\n" +
	"\bendpoint\x18\x01 \x01(\v2\x10.wingsv.EndpointR\bendpoint\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x1d\n" +
	"\athreads\x18\x03 \x01(\rH\x00R\athreads\x88\x01\x01\x12\x1c\n" +
	"\ause_udp\x18\x04 \x01(\bH\x01R\x06useUdp\x88\x01\x01\x12*\n" +
	"\x0eno_obfuscation\x18\x05 \x01(\bH\x02R\rnoObfuscation\x88\x01\x01\x127\n" +
	"\x0elocal_endpoint\x18\x06 \x01(\v2\x10.wingsv.EndpointR\rlocalEndpoint\x12\x12\n" +
	"\x04host\x18\a \x01(\tR\x04host\x12\x17\n" +
	"\x04port\x18\b \x01(\rH\x03R\x04port\x88\x01\x01\x12:\n" +
	"\fsession_mode\x18\t \x01(\x0e2\x17.wingsv.TurnSessionModeR\vsessionModeB\n" +
	"\n" +
	"\b_threadsB\n" +
	"\n" +
	"\b_use_udpB\x11\n" +
	"\x0f_no_obfuscationB\a\n" +
	"\x05_port\"V\n" +
	"\tWireGuard\x12'\n" +
	"\x05iface\x18\x01 \x01(\v2\x11.wingsv.InterfaceR\x05iface\x12 \n" +
	"\x04peer\x18\x02 \x01(\v2\f.wingsv.PeerR\x04peer\"s\n" +
	"\tInterface\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\fR\n" +
	"privateKey\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\x12\x10\n" +
	"\x03dns\x18\x03 \x03(\tR\x03dns\x12\x15\n" +
	"\x03mtu\x18\x04 \x01(\rH\x00R\x03mtu\x88\x01\x01B\x06\n" +
	"\x04_mtu\"y\n" +
	"\x04Peer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12#\n" +
	"\rpreshared_key\x18\x02 \x01(\fR\fpresharedKey\x12-\n" +
	"\vallowed_ips\x18\x03 \x03(\v2\f.wingsv.CidrR\n" +
	"allowedIps\"\xb2\x02\n" +
	"\x04Xray\x12*\n" +
	"\x11active_profile_id\x18\x01 \x01(\tR\x0factiveProfileId\x120\n" +
	"\bprofiles\x18\x02 \x03(\v2\x14.wingsv.VlessProfileR\bprofiles\x12:\n" +
	"\rsubscriptions\x18\x03 \x03(\v2\x14.wingsv.SubscriptionR\rsubscriptions\x120\n" +
	"\bsettings\x18\x04 \x01(\v2\x14.wingsv.XraySettingsR\bsettings\x12+\n" +
	"\x11subscription_json\x18\x05 \x01(\tR\x10subscriptionJson\x12\"\n" +
	"\n" +
	"merge_only\x18\x06 \x01(\bH\x00R\tmergeOnly\x88\x01\x01B\r\n" +
	"\v_merge_only\"\xb4\x02\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1f\n" +
	"\vformat_hint\x18\x04 \x01(\tR\n" +
	"formatHint\x129\n" +
	"\x16refresh_interval_hours\x18\x05 \x01(\rH\x00R\x14refreshIntervalHours\x88\x01\x01\x12$\n" +
	"\vauto_update\x18\x06 \x01(\bH\x01R\n" +
	"autoUpdate\x88\x01\x01\x12+\n" +
	"\x0flast_updated_at\x18\a \x01(\x03H\x02R\rlastUpdatedAt\x88\x01\x01B\x19\n" +
	"\x17_refresh_interval_hoursB\x0e\n" +
	"\f_auto_updateB\x12\n" +
	"\x10_last_updated_at\"\xe3\x01\n" +
	"\fVlessProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\braw_link\x18\x03 \x01(\tR\arawLink\x12'\n" +
	"\x0fsubscription_id\x18\x04 \x01(\tR\x0esubscriptionId\x12-\n" +
	"\x12subscription_title\x18\x05 \x01(\tR\x11subscriptionTitle\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x17\n" +
	"\x04port\x18\a \x01(\rH\x00R\x04port\x88\x01\x01B\a\n" +
	"\x05_port\"\xe6\x02\n" +
	"\fXraySettings\x12 \n" +
	"\tallow_lan\x18\x01 \x01(\bH\x00R\ballowLan\x88\x01\x01\x12*\n" +
	"\x0eallow_insecure\x18\x02 \x01(\bH\x01R\rallowInsecure\x88\x01\x01\x12-\n" +
	"\x10local_proxy_port\x18\x03 \x01(\rH\x02R\x0elocalProxyPort\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"remote_dns\x18\x04 \x01(\tR\tremoteDns\x12\x1d\n" +
	"\n" +
	"direct_dns\x18\x05 \x01(\tR\tdirectDns\x12\x17\n" +
	"\x04ipv6\x18\x06 \x01(\bH\x03R\x04ipv6\x88\x01\x01\x12.\n" +
	"\x10sniffing_enabled\x18\a \x01(\bH\x04R\x0fsniffingEnabled\x88\x01\x01B\f\n" +
	"\n" +
	"_allow_lanB\x11\n" +
	"\x0f_allow_insecureB\x13\n" +
	"\x11_local_proxy_portB\a\n" +
	"\x05_ipv6B\x13\n" +
	"\x11_sniffing_enabled*n\n" +
	"\n" +
	"ConfigType\x12\x1b\n" +
	"\x17CONFIG_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCONFIG_TYPE_VK\x10\x01\x12\x14\n" +
	"\x10CONFIG_TYPE_XRAY\x10\x02\x12\x19\n" +
	"\x15CONFIG_TYPE_AMNEZIAWG\x10\x03*\x82\x01\n" +
	"\vBackendType\x12\x1c\n" +
	"\x18BACKEND_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eBACKEND_TYPE_VK_TURN_WIREGUARD\x10\x01\x12\x15\n" +
	"\x11BACKEND_TYPE_XRAY\x10\x02\x12\x1a\n" +
	"\x16BACKEND_TYPE_AMNEZIAWG\x10\x03*\x8b\x01\n" +
	"\x0fTurnSessionMode\x12!\n" +
	"\x1dTURN_SESSION_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TURN_SESSION_MODE_AUTO\x10\x01\x12\x1e\n" +
	"\x1aTURN_SESSION_MODE_MAINLINE\x10\x02\x12\x19\n" +
	"\x15TURN_SESSION_MODE_MUX\x10\x03BU\n" +
	"\rwings.v.protoB\vWingsvProtoH\x03Z5github.com/mhsanaei/3x-ui/v2/wingsv/proto;wingsvprotob\x06proto3"

var (
	file_wingsv_proto_wingsv_proto_rawDescOnce sync.Once
	file_wingsv_proto_wingsv_proto_rawDescData []byte
)

func file_wingsv_proto_wingsv_proto_rawDescGZIP() []byte {
	file_wingsv_proto_wingsv_proto_rawDescOnce.Do(func() {
		file_wingsv_proto_wingsv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wingsv_proto_wingsv_proto_rawDesc), len(file_wingsv_proto_wingsv_proto_rawDesc)))
	})
	return file_wingsv_proto_wingsv_proto_rawDescData
}

var file_wingsv_proto_wingsv_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_wingsv_proto_wingsv_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_wingsv_proto_wingsv_proto_goTypes = []any{
	(ConfigType)(0),      // 0: wingsv.ConfigType
	(BackendType)(0),     // 1: wingsv.BackendType
	(TurnSessionMode)(0), // 2: wingsv.TurnSessionMode
	(*Config)(nil),       // 3: wingsv.Config
	(*AmneziaWG)(nil),    // 4: wingsv.AmneziaWG
	(*Endpoint)(nil),     // 5: wingsv.Endpoint
	(*Cidr)(nil),         // 6: wingsv.Cidr
	(*Turn)(nil),         // 7: wingsv.Turn
	(*WireGuard)(nil),    // 8: wingsv.WireGuard
	(*Interface)(nil),    // 9: wingsv.Interface
	(*Peer)(nil),         // 10: wingsv.Peer
	(*Xray)(nil),         // 11: wingsv.Xray
	(*Subscription)(nil), // 12: wingsv.Subscription
	(*VlessProfile)(nil), // 13: wingsv.VlessProfile
	(*XraySettings)(nil), // 14: wingsv.XraySettings
}
var file_wingsv_proto_wingsv_proto_depIdxs = []int32{
	0,  // 0: wingsv.Config.type:type_name -> wingsv.ConfigType
	7,  // 1: wingsv.Config.turn:type_name -> wingsv.Turn
	8,  // 2: wingsv.Config.wg:type_name -> wingsv.WireGuard
	1,  // 3: wingsv.Config.backend:type_name -> wingsv.BackendType
	11, // 4: wingsv.Config.xray:type_name -> wingsv.Xray
	4,  // 5: wingsv.Config.awg:type_name -> wingsv.AmneziaWG
	5,  // 6: wingsv.Turn.endpoint:type_name -> wingsv.Endpoint
	5,  // 7: wingsv.Turn.local_endpoint:type_name -> wingsv.Endpoint
	2,  // 8: wingsv.Turn.session_mode:type_name -> wingsv.TurnSessionMode
	9,  // 9: wingsv.WireGuard.iface:type_name -> wingsv.Interface
	10, // 10: wingsv.WireGuard.peer:type_name -> wingsv.Peer
	6,  // 11: wingsv.Peer.allowed_ips:type_name -> wingsv.Cidr
	13, // 12: wingsv.Xray.profiles:type_name -> wingsv.VlessProfile
	12, // 13: wingsv.Xray.subscriptions:type_name -> wingsv.Subscription
	14, // 14: wingsv.Xray.settings:type_name -> wingsv.XraySettings
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_wingsv_proto_wingsv_proto_init() }
func file_wingsv_proto_wingsv_proto_init() {
	if File_wingsv_proto_wingsv_proto != nil {
		return
	}
	file_wingsv_proto_wingsv_proto_msgTypes[4].OneofWrappers = []any{}
	file_wingsv_proto_wingsv_proto_msgTypes[6].OneofWrappers = []any{}
	file_wingsv_proto_wingsv_proto_msgTypes[8].OneofWrappers = []any{}
	file_wingsv_proto_wingsv_proto_msgTypes[9].OneofWrappers = []any{}
	file_wingsv_proto_wingsv_proto_msgTypes[10].OneofWrappers = []any{}
	file_wingsv_proto_wingsv_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wingsv_proto_wingsv_proto_rawDesc), len(file_wingsv_proto_wingsv_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wingsv_proto_wingsv_proto_goTypes,
		DependencyIndexes: file_wingsv_proto_wingsv_proto_depIdxs,
		EnumInfos:         file_wingsv_proto_wingsv_proto_enumTypes,
		MessageInfos:      file_wingsv_proto_wingsv_proto_msgTypes,
	}.Build()
	File_wingsv_proto_wingsv_proto = out.File
	file_wingsv_proto_wingsv_proto_goTypes = nil
	file_wingsv_proto_wingsv_proto_depIdxs = nil
}
