// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/wingsv/panelapi/panel.proto

package panelapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetClientTrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientTrafficRequest) Reset() {
	*x = GetClientTrafficRequest{}
	mi := &file_internal_wingsv_panelapi_panel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientTrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientTrafficRequest) ProtoMessage() {}

func (x *GetClientTrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wingsv_panelapi_panel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientTrafficRequest.ProtoReflect.Descriptor instead.
func (*GetClientTrafficRequest) Descriptor() ([]byte, []int) {
	return file_internal_wingsv_panelapi_panel_proto_rawDescGZIP(), []int{0}
}

func (x *GetClientTrafficRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ClientTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InboundId     int64                  `protobuf:"varint,2,opt,name=inbound_id,json=inboundId,proto3" json:"inbound_id,omitempty"`
	Enable        bool                   `protobuf:"varint,3,opt,name=enable,proto3" json:"enable,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Up            int64                  `protobuf:"varint,5,opt,name=up,proto3" json:"up,omitempty"`
	Down          int64                  `protobuf:"varint,6,opt,name=down,proto3" json:"down,omitempty"`
	ExpiryTime    int64                  `protobuf:"varint,7,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	Total         int64                  `protobuf:"varint,8,opt,name=total,proto3" json:"total,omitempty"`
	LastOnline    int64                  `protobuf:"varint,9,opt,name=last_online,json=lastOnline,proto3" json:"last_online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTraffic) Reset() {
	*x = ClientTraffic{}
	mi := &file_internal_wingsv_panelapi_panel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTraffic) ProtoMessage() {}

func (x *ClientTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wingsv_panelapi_panel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTraffic.ProtoReflect.Descriptor instead.
func (*ClientTraffic) Descriptor() ([]byte, []int) {
	return file_internal_wingsv_panelapi_panel_proto_rawDescGZIP(), []int{1}
}

func (x *ClientTraffic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientTraffic) GetInboundId() int64 {
	if x != nil {
		return x.InboundId
	}
	return 0
}

func (x *ClientTraffic) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *ClientTraffic) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ClientTraffic) GetUp() int64 {
	if x != nil {
		return x.Up
	}
	return 0
}

func (x *ClientTraffic) GetDown() int64 {
	if x != nil {
		return x.Down
	}
	return 0
}

func (x *ClientTraffic) GetExpiryTime() int64 {
	if x != nil {
		return x.ExpiryTime
	}
	return 0
}

func (x *ClientTraffic) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ClientTraffic) GetLastOnline() int64 {
	if x != nil {
		return x.LastOnline
	}
	return 0
}

type ListOnlineClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOnlineClientsRequest) Reset() {
	*x = ListOnlineClientsRequest{}
	mi := &file_internal_wingsv_panelapi_panel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOnlineClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOnlineClientsRequest) ProtoMessage() {}

func (x *ListOnlineClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wingsv_panelapi_panel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOnlineClientsRequest.ProtoReflect.Descriptor instead.
func (*ListOnlineClientsRequest) Descriptor() ([]byte, []int) {
	return file_internal_wingsv_panelapi_panel_proto_rawDescGZIP(), []int{2}
}

type OnlineClients struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineClients) Reset() {
	*x = OnlineClients{}
	mi := &file_internal_wingsv_panelapi_panel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineClients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineClients) ProtoMessage() {}

func (x *OnlineClients) ProtoReflect() protoreflect.Message {
	mi := &file_internal_wingsv_panelapi_panel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineClients.ProtoReflect.Descriptor instead.
func (*OnlineClients) Descriptor() ([]byte, []int) {
	return file_internal_wingsv_panelapi_panel_proto_rawDescGZIP(), []int{3}
}

func (x *OnlineClients) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

var File_internal_wingsv_panelapi_panel_proto protoreflect.FileDescriptor

const file_internal_wingsv_panelapi_panel_proto_rawDesc = "" +
	"\n" +
	"$internal/wingsv/panelapi/panel.proto\x12\x0fwingsv.panel.v1\"/\n" +
	"\x17GetClientTrafficRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xe8\x01\n" +
	"\rClientTraffic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"inbound_id\x18\x02 \x01(\x03R\tinboundId\x12\x16\n" +
	"\x06enable\x18\x03 \x01(\bR\x06enable\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x0e\n" +
	"\x02up\x18\x05 \x01(\x03R\x02up\x12\x12\n" +
	"\x04down\x18\x06 \x01(\x03R\x04down\x12\x1f\n" +
	"\vexpiry_time\x18\a \x01(\x03R\n" +
	"expiryTime\x12\x14\n" +
	"\x05total\x18\b \x01(\x03R\x05total\x12\x1f\n" +
	"\vlast_online\x18\t \x01(\x03R\n" +
	"lastOnline\"\x1a\n" +
	"\x18ListOnlineClientsRequest\"'\n" +
	"\rOnlineClients\x12\x16\n" +
	"\x06emails\x18\x01 \x03(\tR\x06emails2\xc5\x01\n" +
	"\x05Panel\x12\\\n" +
	"\x10GetClientTraffic\x12(.wingsv.panel.v1.GetClientTrafficRequest\x1a\x1e.wingsv.panel.v1.ClientTraffic\x12^\n" +
	"\x11ListOnlineClients\x12).wingsv.panel.v1.ListOnlineClientsRequest\x1a\x1e.wingsv.panel.v1.OnlineClientsB@Z>github.com/mhsanaei/3x-ui/v3/internal/wingsv/panelapi;panelapib\x06proto3"

var (
	file_internal_wingsv_panelapi_panel_proto_rawDescOnce sync.Once
	file_internal_wingsv_panelapi_panel_proto_rawDescData []byte
)

func file_internal_wingsv_panelapi_panel_proto_rawDescGZIP() []byte {
	file_internal_wingsv_panelapi_panel_proto_rawDescOnce.Do(func() {
		file_internal_wingsv_panelapi_panel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_wingsv_panelapi_panel_proto_rawDesc), len(file_internal_wingsv_panelapi_panel_proto_rawDesc)))
	})
	return file_internal_wingsv_panelapi_panel_proto_rawDescData
}

var file_internal_wingsv_panelapi_panel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_wingsv_panelapi_panel_proto_goTypes = []any{
	(*GetClientTrafficRequest)(nil),  // 0: wingsv.panel.v1.GetClientTrafficRequest
	(*ClientTraffic)(nil),            // 1: wingsv.panel.v1.ClientTraffic
	(*ListOnlineClientsRequest)(nil), // 2: wingsv.panel.v1.ListOnlineClientsRequest
	(*OnlineClients)(nil),            // 3: wingsv.panel.v1.OnlineClients
}
var file_internal_wingsv_panelapi_panel_proto_depIdxs = []int32{
	0, // 0: wingsv.panel.v1.Panel.GetClientTraffic:input_type -> wingsv.panel.v1.GetClientTrafficRequest
	2, // 1: wingsv.panel.v1.Panel.ListOnlineClients:input_type -> wingsv.panel.v1.ListOnlineClientsRequest
	1, // 2: wingsv.panel.v1.Panel.GetClientTraffic:output_type -> wingsv.panel.v1.ClientTraffic
	3, // 3: wingsv.panel.v1.Panel.ListOnlineClients:output_type -> wingsv.panel.v1.OnlineClients
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_wingsv_panelapi_panel_proto_init() }
func file_internal_wingsv_panelapi_panel_proto_init() {
	if File_internal_wingsv_panelapi_panel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_wingsv_panelapi_panel_proto_rawDesc), len(file_internal_wingsv_panelapi_panel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_wingsv_panelapi_panel_proto_goTypes,
		DependencyIndexes: file_internal_wingsv_panelapi_panel_proto_depIdxs,
		MessageInfos:      file_internal_wingsv_panelapi_panel_proto_msgTypes,
	}.Build()
	File_internal_wingsv_panelapi_panel_proto = out.File
	file_internal_wingsv_panelapi_panel_proto_goTypes = nil
	file_internal_wingsv_panelapi_panel_proto_depIdxs = nil
}
