// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: internal/wingsv/panelapi/panel.proto

package panelapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Panel_GetClientTraffic_FullMethodName  = "/wingsv.panel.v1.Panel/GetClientTraffic"
	Panel_ListOnlineClients_FullMethodName = "/wingsv.panel.v1.Panel/ListOnlineClients"
)

// PanelClient is the client API for Panel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PanelClient interface {
	GetClientTraffic(ctx context.Context, in *GetClientTrafficRequest, opts ...grpc.CallOption) (*ClientTraffic, error)
	ListOnlineClients(ctx context.Context, in *ListOnlineClientsRequest, opts ...grpc.CallOption) (*OnlineClients, error)
}

type panelClient struct {
	cc grpc.ClientConnInterface
}

func NewPanelClient(cc grpc.ClientConnInterface) PanelClient {
	return &panelClient{cc}
}

func (c *panelClient) GetClientTraffic(ctx context.Context, in *GetClientTrafficRequest, opts ...grpc.CallOption) (*ClientTraffic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientTraffic)
	err := c.cc.Invoke(ctx, Panel_GetClientTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *panelClient) ListOnlineClients(ctx context.Context, in *ListOnlineClientsRequest, opts ...grpc.CallOption) (*OnlineClients, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineClients)
	err := c.cc.Invoke(ctx, Panel_ListOnlineClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PanelServer is the server API for Panel service.
// All implementations must embed UnimplementedPanelServer
// for forward compatibility.
type PanelServer interface {
	GetClientTraffic(context.Context, *GetClientTrafficRequest) (*ClientTraffic, error)
	ListOnlineClients(context.Context, *ListOnlineClientsRequest) (*OnlineClients, error)
	mustEmbedUnimplementedPanelServer()
}

// UnimplementedPanelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPanelServer struct{}

func (UnimplementedPanelServer) GetClientTraffic(context.Context, *GetClientTrafficRequest) (*ClientTraffic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientTraffic not implemented")
}
func (UnimplementedPanelServer) ListOnlineClients(context.Context, *ListOnlineClientsRequest) (*OnlineClients, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOnlineClients not implemented")
}
func (UnimplementedPanelServer) mustEmbedUnimplementedPanelServer() {}
func (UnimplementedPanelServer) testEmbeddedByValue()               {}

// UnsafePanelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PanelServer will
// result in compilation errors.
type UnsafePanelServer interface {
	mustEmbedUnimplementedPanelServer()
}

func RegisterPanelServer(s grpc.ServiceRegistrar, srv PanelServer) {
	// If the following call pancis, it indicates UnimplementedPanelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Panel_ServiceDesc, srv)
}

func _Panel_GetClientTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanelServer).GetClientTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Panel_GetClientTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanelServer).GetClientTraffic(ctx, req.(*GetClientTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Panel_ListOnlineClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOnlineClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanelServer).ListOnlineClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Panel_ListOnlineClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanelServer).ListOnlineClients(ctx, req.(*ListOnlineClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Panel_ServiceDesc is the grpc.ServiceDesc for Panel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Panel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wingsv.panel.v1.Panel",
	HandlerType: (*PanelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientTraffic",
			Handler:    _Panel_GetClientTraffic_Handler,
		},
		{
			MethodName: "ListOnlineClients",
			Handler:    _Panel_ListOnlineClients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/wingsv/panelapi/panel.proto",
}
